### ISSUE TITLE
Springroll Seed -- Phaser3

### ISSUE THREAD

**Issue by pieshop** [SpringRoll/Springroll-Seed#22]
Hi

It seems there is an issue with the [Phaser 3 template branch](https://github.com/SpringRoll/Springroll-Seed/tree/templates/phaser3) of springroll-seed.

It's using the v2 branch of springroll in package.json, but appears to make use of scale manager code being developed in the [safe-scaling branch](https://github.com/SpringRoll/SpringRoll/tree/feature/v2/safe-scaling).

* CameraPositioner imports [scale-manager/ScaledEntity](https://github.com/SpringRoll/SpringRoll/blob/feature/v2/safe-scaling/src/scale-manager/ScaledEntity.js) which isn't yet in [the v2 branch](https://github.com/SpringRoll/SpringRoll/tree/v2/src/scale-manager)
* ScaleManagerPlugin plus a couple of scenes make use of addEntity/removeEntity.

If I update package.json to point at the safe-scaling branch:

`"springroll": "git+https://github.com/SpringRoll/SpringRoll.git#feature/v2/safe-scaling"`

The template compiles but throws errors in the browser.

**Comment by jeremymccurdy-redspace** [comment]
Closing out this issue as safe scaling has been part of V2 for quite a long time and is functioning in the Phaser branch.
